# Generated by Django 4.1.3 on 2023-01-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_rename_post_pagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='fecha_posteo',
            field=models.DateField(auto_now_add=True),
        ),
    ]
