# Generated by Django 4.1.3 on 2023-01-08 22:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_pagina_fecha_posteo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
