# Generated by Django 4.1.3 on 2023-01-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_remove_pagina_imagen_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
    ]
