# Generated by Django 4.1.3 on 2023-01-11 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_remove_pagina_imagen_imagenpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenpost',
            old_name='autor',
            new_name='Pagina',
        ),
    ]
