# Generated by Django 4.1.3 on 2023-01-11 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_imagenpost_fecha_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagenpost',
        ),
    ]
