# Generated by Django 4.1.3 on 2023-01-13 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_imagenpagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='actualizado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
