# Generated by Django 4.1.3 on 2023-01-14 00:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_pagina_actualizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenpagina',
            name='user',
        ),
        migrations.AddField(
            model_name='imagenpagina',
            name='pagina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Blog.pagina'),
            preserve_default=False,
        ),
    ]
