# Generated by Django 4.1.3 on 2023-01-14 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_remove_imagenpagina_user_imagenpagina_pagina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenpagina',
            old_name='imagenpagina',
            new_name='imgpost',
        ),
    ]
