# Generated by Django 4.1.3 on 2023-01-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_rename_imagenpagina_imagenpagina_imgpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenpagina',
            name='imgpost',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
    ]
