# Generated by Django 4.1.3 on 2023-01-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_alter_imagenpagina_imgpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
    ]
