# Generated by Django 4.1.3 on 2023-01-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_remove_pagina_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagina',
            old_name='actualizado',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='pagina',
            old_name='fecha_posteo',
            new_name='editado',
        ),
        migrations.AddField(
            model_name='pagina',
            name='imagen',
            field=models.ImageField(blank=True, default='defaultpost.png', null=True, upload_to='post'),
        ),
        migrations.DeleteModel(
            name='Imagenpagina',
        ),
    ]
