# Generated by Django 4.1.3 on 2023-01-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0017_rename_actualizado_pagina_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
    ]
