# Generated by Django 4.1.3 on 2023-01-16 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_alter_pagina_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagina',
            old_name='autor',
            new_name='usuario',
        ),
    ]
