# Generated by Django 4.1.3 on 2023-01-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0019_rename_autor_pagina_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagina',
            old_name='usuario',
            new_name='user',
        ),
    ]
