# Generated by Django 4.1.3 on 2023-01-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0020_rename_usuario_pagina_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='editado',
            field=models.DateField(auto_now=True),
        ),
    ]
