# Generated by Django 4.1.3 on 2023-01-09 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='web_url',
        ),
    ]
