# Generated by Django 4.1.3 on 2023-01-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_remove_profile_imagen_remove_profile_web_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='imagen_perfil',
        ),
    ]
