# Generated by Django 4.1.3 on 2023-01-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0004_delete_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram',
        ),
        migrations.AddField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
