# Generated by Django 4.1.3 on 2023-01-09 21:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0004_delete_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram',
        ),
        migrations.AddField(
            model_name='profile',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='web_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
