# Generated by Django 4.1.3 on 2023-01-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0005_remove_profile_descripcion_remove_profile_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
