# Generated by Django 4.1.3 on 2023-01-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0005_remove_profile_facebook_remove_profile_instagram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imagen',
            new_name='avatar',
        ),
    ]
