# Generated by Django 4.1.3 on 2023-01-12 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0005_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
