# Generated by Django 4.1.3 on 2023-01-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0006_rename_imagen_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='web_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
