# Generated by Django 4.1.3 on 2023-01-12 23:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0007_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='user',
        ),
        migrations.AddField(
            model_name='avatar',
            name='Profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Registro.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
