# Generated by Django 4.1.3 on 2023-01-10 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0008_rename_perfil_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
