# Generated by Django 4.1.3 on 2023-01-12 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0009_remove_avatar_profile_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram',
        ),
    ]
