# Generated by Django 4.1.3 on 2023-01-13 00:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0010_remove_profile_facebook_remove_profile_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
