# Generated by Django 4.1.3 on 2023-01-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0011_alter_profile_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='web_site',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
