# Generated by Django 4.1.3 on 2023-01-15 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0013_profile_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='autor',
            new_name='user',
        ),
    ]
