# Generated by Django 4.1.3 on 2023-01-15 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0014_rename_autor_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='autor',
        ),
    ]
