# Generated by Django 4.1.3 on 2023-01-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0017_rename_user_profile_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='user',
            new_name='usuario',
        ),
    ]
