# Generated by Django 4.1.3 on 2023-01-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0018_rename_user_avatar_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='usuario',
            new_name='user',
        ),
    ]
