# Generated by Django 4.1.3 on 2023-01-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0021_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
