# Generated by Django 4.1.3 on 2023-01-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0025_mensajesalida_mensajeentrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajeentrada',
            name='leido',
        ),
        migrations.RemoveField(
            model_name='mensajesalida',
            name='leido',
        ),
    ]
