# Generated by Django 4.1.3 on 2023-01-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0026_remove_mensajeentrada_leido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeentrada',
            name='cuerpo',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mensajesalida',
            name='cuerpo',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
