# Generated by Django 4.1.3 on 2023-01-17 20:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0027_alter_mensajeentrada_cuerpo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajesalida',
            name='receptor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Registro.mensajeentrada'),
            preserve_default=False,
        ),
    ]
