# Generated by Django 4.1.3 on 2023-01-17 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0028_mensajesalida_receptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajesalida',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.profile'),
        ),
    ]
