# Generated by Django 4.1.3 on 2023-01-17 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Registro', '0029_alter_mensajesalida_receptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajesalida',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.mensajesalida'),
        ),
        migrations.AlterField(
            model_name='mensajesalida',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
