# Generated by Django 4.1.3 on 2023-01-17 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Registro', '0030_alter_mensajesalida_emisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajesalida',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajesalida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensajesalida',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to=settings.AUTH_USER_MODEL),
        ),
    ]
