# Generated by Django 4.1.3 on 2023-01-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0034_alter_profile_email_alter_profile_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
